insert into item_templates (id, name, kind, slot, rarity, price, stackable, stats) values
  ('pill_cultivate', '培养丹', 'consumable', null, 'rare', 120, true, '{"exp":10000}'),
  ('pill_insight', '悟性丹', 'material', null, 'epic', 500, true, '{}'),

  ('sword_wood', '木剑', 'weapon', 'weapon', 'common', 120, false, '{"atk":3,"tier":1,"score":8}'),
  ('armor_cloth', '布衣', 'armor', 'chest', 'common', 160, false, '{"def":3,"hp":35,"tier":1,"score":10}'),
  ('ring_copper', '青铜戒指', 'accessory', 'ring_left', 'uncommon', 260, false, '{"atk":2,"luck":1,"tier":1,"score":12}'),
  ('blade_green_t1', '青锋剑', 'weapon', 'weapon', 'uncommon', 620, false, '{"atk":10,"luck":1,"tier":1,"score":20}'),
  ('armor_jade_t1', '青玉法衣', 'armor', 'chest', 'uncommon', 680, false, '{"def":8,"hp":80,"mdef":2,"tier":1,"score":24}'),
  ('helm_bronze_t1', '青铜头盔', 'armor', 'head', 'uncommon', 520, false, '{"def":5,"hp":50,"tier":1,"score":14}'),
  ('boots_deerskin_t1', '鹿皮靴', 'armor', 'feet', 'uncommon', 480, false, '{"def":3,"luck":2,"tier":1,"score":12}'),
  ('bracelet_guard_t1', '守备手镯', 'accessory', 'bracelet_left', 'uncommon', 540, false, '{"atk":3,"def":2,"tier":1,"score":15}'),

  ('blade_darkiron_t2', '玄铁剑', 'weapon', 'weapon', 'rare', 1400, false, '{"atk":22,"mag":3,"tier":2,"score":46}'),
  ('armor_cloud_t2', '云纹玄甲', 'armor', 'chest', 'rare', 1500, false, '{"def":18,"hp":170,"mdef":4,"tier":2,"score":54}'),
  ('ring_sea_t2', '碧海灵戒', 'accessory', 'ring_left', 'rare', 1700, false, '{"atk":10,"mag":7,"hp":90,"luck":4,"tier":2,"score":48}'),
  ('neck_jade_t2', '青玉项链', 'accessory', 'neck', 'rare', 1600, false, '{"mag":10,"hp":90,"luck":3,"tier":2,"score":44}'),
  ('bracelet_tiger_t2', '虎牙手镯', 'accessory', 'bracelet_left', 'rare', 1500, false, '{"atk":12,"luck":5,"tier":2,"score":45}'),
  ('blade_serpent_t2', '蛇纹剑', 'weapon', 'weapon', 'rare', 1900, false, '{"atk":26,"luck":4,"tier":2,"score":58}'),
  ('belt_snake_t2', '蛇鳞腰带', 'armor', 'waist', 'rare', 1320, false, '{"def":10,"mdef":5,"hp":120,"tier":2,"score":42}'),
  ('boots_cloud_t2', '流云靴', 'armor', 'feet', 'rare', 1260, false, '{"def":8,"luck":5,"hp":80,"tier":2,"score":38}'),

  ('blade_flame_t3', '赤焰神兵', 'weapon', 'weapon', 'epic', 3600, false, '{"atk":42,"mag":8,"luck":6,"tier":3,"score":96}'),
  ('armor_star_t3', '星辉战袍', 'armor', 'chest', 'epic', 3800, false, '{"def":38,"hp":420,"mdef":10,"tier":3,"score":116}'),
  ('ring_thunder_t3', '紫霄雷戒', 'accessory', 'ring_left', 'epic', 4200, false, '{"atk":22,"mag":16,"hp":230,"luck":8,"crit_pct":1,"tier":3,"score":112}'),
  ('armor_woma_t3', '沃玛战甲', 'armor', 'chest', 'epic', 4300, false, '{"def":46,"hp":480,"mdef":12,"tier":3,"score":128}'),
  ('helm_woma_t3', '沃玛头盔', 'armor', 'head', 'epic', 3900, false, '{"def":34,"hp":300,"tier":3,"score":96}'),
  ('neck_woma_t3', '沃玛项链', 'accessory', 'neck', 'epic', 4200, false, '{"atk":20,"mag":20,"luck":8,"tier":3,"score":108}'),
  ('bracelet_woma_t3', '沃玛手镯', 'accessory', 'bracelet_right', 'epic', 4100, false, '{"atk":18,"def":8,"mdef":6,"tier":3,"score":102}'),
  ('boots_woma_t3', '沃玛战靴', 'armor', 'feet', 'epic', 3600, false, '{"def":24,"luck":9,"hp":220,"tier":3,"score":88}'),

  ('blade_dragon_t4', '龙吟镇河剑', 'weapon', 'weapon', 'legendary', 9000, false, '{"atk":82,"mag":14,"luck":12,"crit_pct":2,"tier":4,"score":210}'),
  ('armor_phoenix_t4', '凤舞九天甲', 'armor', 'chest', 'legendary', 9600, false, '{"def":82,"hp":880,"mdef":22,"tier":4,"score":248}'),
  ('ring_sun_t4', '大日鸿蒙戒', 'accessory', 'ring_left', 'legendary', 10800, false, '{"atk":46,"mag":34,"hp":480,"luck":16,"crit_pct":2,"tier":4,"score":252}'),
  ('blade_purgatory_t4', '炼狱战刃', 'weapon', 'weapon', 'legendary', 11800, false, '{"atk":98,"luck":14,"heavy_hit_pct":2,"tier":4,"score":270}'),
  ('armor_dragon_t4', '龙鳞战甲', 'armor', 'chest', 'legendary', 11600, false, '{"def":98,"mdef":28,"hp":1100,"tier":4,"score":292}'),
  ('ring_zuma_t4', '祖玛神戒', 'accessory', 'ring_right', 'legendary', 9800, false, '{"atk":52,"mag":38,"hp":540,"luck":14,"crit_pct":2,"tier":4,"score":266}'),
  ('helm_zuma_t4', '祖玛头盔', 'armor', 'head', 'legendary', 9200, false, '{"def":68,"hp":650,"mdef":12,"tier":4,"score":216}'),
  ('bracelet_zuma_t4', '祖玛手镯', 'accessory', 'bracelet_left', 'legendary', 9400, false, '{"atk":38,"mag":28,"luck":15,"tier":4,"score":224}'),

  ('blade_cangyue_t5', '苍月破军刃', 'weapon', 'weapon', 'supreme', 32000, false, '{"atk":150,"mag":28,"luck":24,"crit_pct":3,"heavy_hit_pct":3,"tier":5,"score":430}'),
  ('armor_bull_t5', '牛魔王战甲', 'armor', 'chest', 'supreme', 34000, false, '{"def":150,"mdef":58,"hp":1800,"tier":5,"score":470}'),
  ('neck_nether_t5', '黄泉镇魂链', 'accessory', 'neck', 'supreme', 30000, false, '{"atk":74,"mag":74,"hp":920,"luck":26,"crit_pct":3,"tier":5,"score":430}'),
  ('boss_relic_blade', '赤焰凰血剑', 'weapon', 'weapon', 'supreme', 30000, false, '{"atk":132,"mag":28,"luck":22,"life_steal_pct":2,"tier":5,"score":380}'),
  ('boss_relic_armor', '九转玄火甲', 'armor', 'chest', 'supreme', 30000, false, '{"def":132,"mdef":46,"hp":1580,"tier":5,"score":405}'),
  ('ring_bull_t5', '牛魔王指环', 'accessory', 'ring_right', 'supreme', 28000, false, '{"atk":64,"mag":48,"hp":760,"luck":25,"crit_pct":3,"tier":5,"score":390}'),
  ('bracelet_nether_t5', '黄泉手镯', 'accessory', 'bracelet_right', 'supreme', 26000, false, '{"atk":58,"def":30,"mdef":22,"luck":24,"tier":5,"score":360}'),
  ('boots_cangyue_t5', '苍月战靴', 'armor', 'feet', 'supreme', 24000, false, '{"def":80,"hp":700,"luck":28,"tier":5,"score":320}'),

  ('blade_soul_t6', '镇魂天刃', 'weapon', 'weapon', 'supreme', 46000, false, '{"atk":198,"mag":42,"luck":34,"crit_pct":4,"heavy_hit_pct":4,"tier":6,"score":560}'),
  ('armor_soul_t6', '镇魂战甲', 'armor', 'chest', 'supreme', 48000, false, '{"def":205,"mdef":76,"hp":2400,"tier":6,"score":620}'),
  ('helm_soul_t6', '镇魂头盔', 'armor', 'head', 'supreme', 42000, false, '{"def":116,"mdef":30,"hp":980,"tier":6,"score":420}'),
  ('ring_soul_t6', '镇魂戒', 'accessory', 'ring_left', 'supreme', 43000, false, '{"atk":88,"mag":72,"hp":980,"luck":36,"crit_pct":4,"tier":6,"score":500}'),
  ('neck_soul_t6', '镇魂项链', 'accessory', 'neck', 'supreme', 43000, false, '{"atk":82,"mag":92,"luck":36,"life_steal_pct":2,"tier":6,"score":500}'),
  ('bracelet_soul_t6', '镇魂手镯', 'accessory', 'bracelet_left', 'supreme', 41000, false, '{"atk":78,"def":46,"mdef":34,"luck":34,"tier":6,"score":470}'),

  ('blade_starfall_t7', '星陨斩龙刃', 'weapon', 'weapon', 'ultimate', 68000, false, '{"atk":260,"mag":58,"luck":48,"crit_pct":5,"heavy_hit_pct":5,"tier":7,"score":760}'),
  ('armor_starfall_t7', '星陨龙甲', 'armor', 'chest', 'ultimate', 70000, false, '{"def":270,"mdef":105,"hp":3300,"tier":7,"score":840}'),
  ('helm_starfall_t7', '星陨冠', 'armor', 'head', 'ultimate', 61000, false, '{"def":150,"mdef":42,"hp":1320,"luck":24,"tier":7,"score":570}'),
  ('ring_starfall_t7', '星陨戒', 'accessory', 'ring_right', 'ultimate', 62000, false, '{"atk":116,"mag":96,"hp":1280,"luck":50,"crit_pct":5,"tier":7,"score":680}'),
  ('neck_starfall_t7', '星陨链', 'accessory', 'neck', 'ultimate', 62000, false, '{"atk":108,"mag":122,"luck":50,"life_steal_pct":3,"tier":7,"score":690}'),
  ('bracelet_starfall_t7', '星陨手镯', 'accessory', 'bracelet_right', 'ultimate', 59000, false, '{"atk":105,"def":64,"mdef":48,"luck":48,"tier":7,"score":640}'),

  ('blade_void_t8', '虚空裂魂刃', 'weapon', 'weapon', 'ultimate', 92000, false, '{"atk":340,"mag":76,"luck":66,"crit_pct":6,"heavy_hit_pct":7,"life_steal_pct":3,"tier":8,"score":980}'),
  ('armor_void_t8', '虚空玄甲', 'armor', 'chest', 'ultimate', 96000, false, '{"def":355,"mdef":142,"hp":4500,"paralyze_pct":1,"tier":8,"score":1080}'),
  ('helm_void_t8', '虚空战盔', 'armor', 'head', 'ultimate', 85000, false, '{"def":198,"mdef":58,"hp":1800,"luck":34,"tier":8,"score":740}'),
  ('ring_void_t8', '虚空神戒', 'accessory', 'ring_left', 'ultimate', 86000, false, '{"atk":154,"mag":130,"hp":1720,"luck":70,"crit_pct":6,"tier":8,"score":870}'),
  ('neck_void_t8', '虚空项链', 'accessory', 'neck', 'ultimate', 86000, false, '{"atk":145,"mag":162,"luck":70,"life_steal_pct":4,"tier":8,"score":890}'),
  ('bracelet_void_t8', '虚空手镯', 'accessory', 'bracelet_left', 'ultimate', 83000, false, '{"atk":142,"def":88,"mdef":66,"luck":66,"heavy_hit_pct":3,"tier":8,"score":830}'),

  ('blade_god_t9', '神阶开天刃', 'weapon', 'weapon', 'ultimate', 130000, false, '{"atk":450,"mag":102,"luck":92,"crit_pct":8,"heavy_hit_pct":10,"life_steal_pct":4,"paralyze_pct":2,"tier":9,"score":1320}'),
  ('armor_god_t9', '神阶不灭甲', 'armor', 'chest', 'ultimate', 136000, false, '{"def":470,"mdef":190,"hp":6200,"paralyze_pct":2,"tier":9,"score":1450}'),
  ('helm_god_t9', '神阶天罡盔', 'armor', 'head', 'ultimate', 118000, false, '{"def":260,"mdef":82,"hp":2500,"luck":48,"tier":9,"score":980}'),
  ('ring_god_t9', '神阶天命戒', 'accessory', 'ring_right', 'ultimate', 120000, false, '{"atk":205,"mag":176,"hp":2380,"luck":96,"crit_pct":8,"life_steal_pct":3,"tier":9,"score":1180}'),
  ('neck_god_t9', '神阶镇界链', 'accessory', 'neck', 'ultimate', 120000, false, '{"atk":198,"mag":220,"luck":96,"life_steal_pct":5,"heavy_hit_pct":4,"tier":9,"score":1200}'),
  ('bracelet_god_t9', '神阶灭魂镯', 'accessory', 'bracelet_right', 'ultimate', 116000, false, '{"atk":192,"def":118,"mdef":90,"luck":92,"crit_pct":4,"heavy_hit_pct":5,"tier":9,"score":1120}'),

  ('blade_immortal_t10', '仙阶太初剑', 'weapon', 'weapon', 'ultimate', 190000, false, '{"atk":620,"mag":150,"luck":130,"crit_pct":11,"heavy_hit_pct":14,"life_steal_pct":6,"paralyze_pct":4,"tier":10,"score":1820}'),
  ('armor_immortal_t10', '仙阶万劫甲', 'armor', 'chest', 'ultimate', 200000, false, '{"def":650,"mdef":265,"hp":8800,"paralyze_pct":4,"tier":10,"score":2000}'),
  ('helm_immortal_t10', '仙阶太玄冠', 'armor', 'head', 'ultimate', 176000, false, '{"def":360,"mdef":116,"hp":3600,"luck":70,"tier":10,"score":1360}'),
  ('ring_immortal_t10', '仙阶长生戒', 'accessory', 'ring_left', 'ultimate', 180000, false, '{"atk":285,"mag":245,"hp":3400,"luck":136,"crit_pct":10,"life_steal_pct":5,"tier":10,"score":1640}'),
  ('neck_immortal_t10', '仙阶归墟链', 'accessory', 'neck', 'ultimate', 180000, false, '{"atk":275,"mag":310,"luck":136,"life_steal_pct":7,"heavy_hit_pct":6,"tier":10,"score":1680}'),
  ('bracelet_immortal_t10', '仙阶破界镯', 'accessory', 'bracelet_left', 'ultimate', 172000, false, '{"atk":265,"def":165,"mdef":125,"luck":130,"crit_pct":6,"heavy_hit_pct":8,"paralyze_pct":2,"tier":10,"score":1580}')
on conflict (id) do update set
  name = excluded.name,
  kind = excluded.kind,
  slot = excluded.slot,
  rarity = excluded.rarity,
  price = excluded.price,
  stackable = excluded.stackable,
  stats = excluded.stats;

insert into skills (id, name, class, min_level, mp_cost, cooldown_ms, config) values
  ('basic_sword', '攻杀剑术', 'warrior', 1, 0, 0, '{"kind":"passive","type":"战士基础","desc":"被动增加攻击、防御，前期稳定提升近战强度。","source":"比奇新手村、比奇森林、无尽塔低层","book_id":"book_basic_sword","requires_book":true,"atk_bonus":3,"def_bonus":1}'),
  ('warrior_body', '铁布衫', 'warrior', 8, 0, 0, '{"kind":"passive","type":"战士防护","desc":"被动增加物理防御和生命。","source":"比奇矿洞、尸王、无尽塔 5 层后","book_id":"book_warrior_body","requires_book":true,"def_bonus":3,"hp_bonus":22}'),
  ('halfmoon_blade', '半月弯刀', 'warrior', 18, 0, 0, '{"kind":"passive","type":"战士进阶","desc":"被动增加攻击和幸运，兼顾输出与掉落倾向。","source":"毒蛇山谷、沃玛森林、沃玛神庙","book_id":"book_halfmoon_blade","requires_book":true,"atk_bonus":5,"luck_bonus":1}'),
  ('flame_blade', '烈火剑意', 'warrior', 28, 0, 0, '{"kind":"passive","type":"战士高阶","desc":"被动增加攻击、生命和暴击。","source":"盟重祖玛神庙、世界首领、苍月岛高阶怪物","book_id":"book_flame_blade","requires_book":true,"atk_bonus":7,"hp_bonus":18,"crit_pct_bonus":1}'),

  ('fireball', '火球精通', 'mage', 1, 0, 0, '{"kind":"passive","type":"法师基础","desc":"被动增加魔法攻击和魔法上限。","source":"比奇新手村、比奇森林、无尽塔低层","book_id":"book_fireball","requires_book":true,"mag_bonus":4,"mp_bonus":14}'),
  ('magic_shield', '魔法盾理', 'mage', 8, 0, 0, '{"kind":"passive","type":"法师防护","desc":"被动增加魔法防御、生命和魔法上限。","source":"比奇矿洞、尸王、无尽塔 5 层后","book_id":"book_magic_shield","requires_book":true,"mdef_bonus":3,"hp_bonus":14,"mp_bonus":18}'),
  ('lightning_master', '雷电术精通', 'mage', 18, 0, 0, '{"kind":"passive","type":"法师进阶","desc":"被动增加魔法攻击和幸运。","source":"毒蛇山谷、沃玛神庙","book_id":"book_lightning_master","requires_book":true,"mag_bonus":6,"luck_bonus":1}'),
  ('ice_roar', '冰咆哮心法', 'mage', 30, 0, 0, '{"kind":"passive","type":"法师高阶","desc":"被动增加魔法攻击、魔法上限和魔法防御。","source":"盟重祖玛神庙、苍月岛秘境、世界首领","book_id":"book_ice_roar","requires_book":true,"mag_bonus":8,"mp_bonus":28,"mdef_bonus":1}'),

  ('healing_charm', '治愈心法', 'taoist', 1, 0, 0, '{"kind":"passive","type":"道士基础","desc":"被动增加生命、魔法防御和少量魔法攻击。","source":"比奇新手村、比奇森林、无尽塔低层","book_id":"book_healing_charm","requires_book":true,"hp_bonus":28,"mdef_bonus":2,"mag_bonus":1}'),
  ('spirit_talisman', '灵魂火符', 'taoist', 8, 0, 0, '{"kind":"passive","type":"道士攻击","desc":"被动增加魔法攻击和少量攻击。","source":"比奇矿洞、尸王、无尽塔 5 层后","book_id":"book_spirit_talisman","requires_book":true,"mag_bonus":4,"atk_bonus":1}'),
  ('summon_guard', '召唤契约', 'taoist', 18, 0, 0, '{"kind":"passive","type":"道士生存","desc":"被动增加生命、物理防御和魔法防御。","source":"毒蛇山谷、沃玛神庙","book_id":"book_summon_guard","requires_book":true,"hp_bonus":40,"def_bonus":2,"mdef_bonus":2}'),
  ('poison_lore', '施毒心经', 'taoist', 28, 0, 0, '{"kind":"passive","type":"道士高阶","desc":"被动增加魔法攻击、幸运和暴击。","source":"盟重祖玛神庙、世界首领、苍月岛高阶怪物","book_id":"book_poison_lore","requires_book":true,"mag_bonus":5,"luck_bonus":2,"crit_pct_bonus":1}'),

  ('shadow_step', '影袭身法', 'assassin', 1, 0, 0, '{"kind":"passive","type":"刺客基础","desc":"被动增加攻击、幸运和暴击。","source":"比奇新手村、比奇森林、无尽塔低层","book_id":"book_shadow_step","requires_book":true,"atk_bonus":3,"luck_bonus":2,"crit_pct_bonus":1}'),
  ('night_blade', '夜刃诀', 'assassin', 8, 0, 0, '{"kind":"passive","type":"刺客攻击","desc":"被动增加攻击和幸运。","source":"比奇矿洞、尸王、无尽塔 5 层后","book_id":"book_night_blade","requires_book":true,"atk_bonus":5,"luck_bonus":1}'),
  ('ghost_body', '鬼步', 'assassin', 18, 0, 0, '{"kind":"passive","type":"刺客身法","desc":"被动增加幸运、物理防御和魔法防御。","source":"毒蛇山谷、沃玛神庙","book_id":"book_ghost_body","requires_book":true,"luck_bonus":4,"def_bonus":1,"mdef_bonus":1}'),
  ('blood_mark', '血印', 'assassin', 28, 0, 0, '{"kind":"passive","type":"刺客高阶","desc":"被动增加攻击、生命和暴击。","source":"盟重祖玛神庙、世界首领、苍月岛高阶怪物","book_id":"book_blood_mark","requires_book":true,"atk_bonus":6,"hp_bonus":18,"crit_pct_bonus":1}'),

  ('focus_breath', '凝神诀', 'all', 3, 0, 0, '{"kind":"passive","type":"通用基础","desc":"被动增加攻魔、防御、生命和魔法。","source":"比奇城区任务、比奇野外、无尽塔低层","book_id":"book_focus_breath","requires_book":true,"atk_bonus":1,"mag_bonus":1,"def_bonus":1,"mdef_bonus":1,"hp_bonus":10,"mp_bonus":8}'),
  ('field_medicine', '战场调息', 'all', 12, 0, 0, '{"kind":"passive","type":"通用生存","desc":"被动增加生命和魔法上限。","source":"毒蛇山谷、矿洞深处、无尽塔 10 层后","book_id":"book_field_medicine","requires_book":true,"hp_bonus":32,"mp_bonus":14}'),
  ('treasure_sense', '寻宝眼', 'all', 20, 0, 0, '{"kind":"passive","type":"通用寻宝","desc":"被动增加幸运和暴击，提升好装备掉落倾向。","source":"沃玛神庙、盟重石墓阵、无尽塔 20 层后","book_id":"book_treasure_sense","requires_book":true,"luck_bonus":3,"crit_pct_bonus":1}'),
  ('iron_will', '百折心法', 'all', 30, 0, 0, '{"kind":"passive","type":"通用高阶","desc":"被动增加生命、物理防御和魔法防御。","source":"盟重祖玛神庙、苍月岛、世界首领","book_id":"book_iron_will","requires_book":true,"hp_bonus":46,"def_bonus":2,"mdef_bonus":2}')
on conflict (id) do update set
  name = excluded.name,
  class = excluded.class,
  min_level = excluded.min_level,
  mp_cost = excluded.mp_cost,
  cooldown_ms = excluded.cooldown_ms,
  config = excluded.config;
