use serde::{Deserialize, Serialize};
use time::OffsetDateTime;

use crate::EntityId;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MobTemplate {
    pub id: String,
    pub name: String,
    pub level: i32,
    pub max_hp: i64,
    pub atk: i64,
    pub def: i64,
    pub exp: i64,
    pub gold: i64,
    pub boss: bool,
    pub respawn_seconds: i32,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MobSpawn {
    pub id: EntityId,
    pub template_id: String,
    pub zone: String,
    pub room: String,
    pub hp: i64,
    pub alive: bool,
    pub respawn_at: Option<OffsetDateTime>,
}

pub fn starter_mobs() -> Vec<MobTemplate> {
    vec![
        MobTemplate {
            id: "chicken".into(),
            name: "鸡".into(),
            level: 1,
            max_hp: 25,
            atk: 3,
            def: 0,
            exp: 8,
            gold: 5,
            boss: false,
            respawn_seconds: 45,
        },
        MobTemplate {
            id: "deer".into(),
            name: "鹿".into(),
            level: 2,
            max_hp: 35,
            atk: 4,
            def: 1,
            exp: 12,
            gold: 8,
            boss: false,
            respawn_seconds: 60,
        },
        MobTemplate {
            id: "sheep".into(),
            name: "羊".into(),
            level: 3,
            max_hp: 48,
            atk: 5,
            def: 1,
            exp: 18,
            gold: 12,
            boss: false,
            respawn_seconds: 60,
        },
        MobTemplate {
            id: "bee".into(),
            name: "毒蜂".into(),
            level: 4,
            max_hp: 62,
            atk: 8,
            def: 2,
            exp: 26,
            gold: 18,
            boss: false,
            respawn_seconds: 75,
        },
        MobTemplate {
            id: "cat".into(),
            name: "钉耙猫".into(),
            level: 4,
            max_hp: 70,
            atk: 9,
            def: 2,
            exp: 30,
            gold: 20,
            boss: false,
            respawn_seconds: 80,
        },
        MobTemplate {
            id: "wolf".into(),
            name: "森林狼".into(),
            level: 5,
            max_hp: 90,
            atk: 11,
            def: 3,
            exp: 35,
            gold: 24,
            boss: false,
            respawn_seconds: 90,
        },
        MobTemplate {
            id: "spider".into(),
            name: "洞穴蜘蛛".into(),
            level: 8,
            max_hp: 130,
            atk: 16,
            def: 5,
            exp: 60,
            gold: 40,
            boss: false,
            respawn_seconds: 110,
        },
        MobTemplate {
            id: "skeleton".into(),
            name: "骷髅".into(),
            level: 9,
            max_hp: 160,
            atk: 18,
            def: 6,
            exp: 80,
            gold: 55,
            boss: false,
            respawn_seconds: 120,
        },
        MobTemplate {
            id: "bug_queen".into(),
            name: "触龙神".into(),
            level: 35,
            max_hp: 12_000,
            atk: 260,
            def: 90,
            exp: 12_000,
            gold: 4_000,
            boss: true,
            respawn_seconds: 3600,
        },
    ]
}
